apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-dashboard-gateway
  namespace: {{ .Values.global.namespace }}
  annotations:
    Release.Name: {{ .Release.Name }}
    Release.Revision: "{{ .Release.Revision }}"
    Chart.Name: {{ .Chart.Name }}
    Chart.Version: {{ .Chart.Version }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: grafana-dashboard-gateway.{{ .Values.global.namespace }}.{{ .Values.global.ingress.domain_name }}
    http:
      paths:
      - backend:
          serviceName: grafana-dashboard-gateway
          servicePort: 5858